version: '2.2'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres:/var/lib/postgres/data/
    env_file:
      - ./.env

  backend:
    image: rasul24/backend:v1.0
    restart: always
    volumes:
      - static_value:/app/back_static/
      - media_value:/app/back_media/
      - docs:/app/api/docs/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: rasul24/frontend:v1.0
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - docs:/usr/share/nginx/html/api/docs/
      - ./ssl/:/etc/nginx/ssl/
      - static_value:/var/html/back_static/
      - media_value:/var/html/back_media/
    restart: always

volumes:
  static_value:
  media_value:
  postgres:
  docs:
