# Generated by Django 4.2 on 2023-05-15 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=0.01, message="Количество должно быть больше нуля!"
                    )
                ],
                verbose_name="Количество",
            ),
        ),
    ]
