# Generated by Django 4.2.1 on 2023-05-30 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_alter_recipe_cooking_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=1,
                        message="Время приготовления не менее одной минуты!",
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=300, message="Очень долго ждать..."
                    ),
                ],
                verbose_name="Время приготовления",
            ),
        ),
    ]
