# Generated by Django 4.2.1 on 2023-06-04 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_alter_recipe_cooking_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Время приготовления не менее одной минуты!"
                    ),
                    django.core.validators.MaxValueValidator(
                        300, message="Очень долго ждать..."
                    ),
                ],
                verbose_name="Время приготовления",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Количество должно быть больше нуля!"
                    ),
                    django.core.validators.MaxValueValidator(
                        100, message="Слишком много!"
                    ),
                ],
                verbose_name="Количество",
            ),
        ),
    ]
